### ISSUE TITLE
C++11 change range size?

### ISSUE THREAD

**Issue by Pursche** [dougbinks/enkiTS#10]
Hi! I have been using EnkiTS in a game engine and it was extremely easy to set up and use! I have an array of say 500 objects that I want to call a function on, I have a total of 16 worker threads (including the main thread I guess) but when I benchmark it it seems to be about 50% slower than running it single threaded. This was worse than expectations so I decided to put a breakpoint inside of the lambda scope and I noticed that range.start and range.end was 4 objects apart. So it seems like EnkiTS split it into 125 chunks of work. I would prefer to try to split this into fewer, larger chunks to get better performance out of it. How would I go about doing this? Ideally I think I would like to have WORKER_THREADS * 1 or 2 chunks of work.

Here's the code inside of my lambda scope
```
[&component_list_pair, delta_time](enki::TaskSetPartition range, uint32_t threadnum)
            {
                for(auto i : Range(range.start, range.end))
                {
                    component_list_pair.second[i]->ParallelUpdate(delta_time);
                }
            }
```

**Comment by dougbinks** [comment]
The approach I use is to make the range iterate over multiple values. So if you want to iterate over 500 objects but want 50 or so to be computed per thread, then set the the set size to be 50 and have an inner loop going over 10 values. You'll need to add a check to ensure you don't go beyond the last value in your actual data set.

I'm considering adding a minimum range size to the interface which should make this easier in the future.

**Comment by dougbinks** [comment]
I have a development branch [C++11 Grainsize](https://github.com/dougbinks/enkiTS/tree/C%2B%2B11_Grainsize) which lets you specify the minimum size you'd like to split tasks into. This also uses a revised partitioning scheme which should be better for CPUs with larger numbers of hardware threads.

This is work in progress and I expect to improve on the partitioning, but I'd appreciate feedback on the branch if you are able to try it out. [See the comments for details](https://github.com/dougbinks/enkiTS/blob/C%2B%2B11_Grainsize/src/TaskScheduler.h#L78-L84) as I've not yet added documentation to the readme nor any examples for this.

**Comment by dougbinks** [comment]
The new grain size feature is now merged with the main branches. I've not heard back from you since the issue was submitted, so I'll close this as I believe it is resolved with the new functionality.
