### ISSUE TITLE
Macro redefinition for WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by BobbyAnguelov** [dougbinks/enkiTS#100]
Ln 50 in TaskScheduler.cpp assumes that the 'WIN32_LEAN_AND_MEAN' and the 'NOMINMAX' macros are not previously defined.

It should read:

```cpp
#ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
#endif

#ifndef NOMINMAX
    #define NOMINMAX
#endif
```

**Comment by dougbinks** [comment]
Good catch. Fix on it's way, thanks!
