### ISSUE TITLE
Put header files in a subdirectory

### ISSUE THREAD

**Issue by bkmgit** [dougbinks/enkiTS#108]
It can be helpful to put header files in a subdirectory to separate them from others in the main include directory.

**Comment by dougbinks** [comment]
This is just a note that I'm leaving this issue open as [you mentioned there was some documentation incoming](https://github.com/dougbinks/enkiTS/pull/110#issuecomment-1848233383https://github.com/dougbinks/enkiTS/pull/110#issuecomment-1848233383).

Do you think the `dev` branch with the #110 can be merged to main and a release made without the documentation?

**Comment by bkmgit** [comment]
Sorry for the delay and thanks for the reminder. https://github.com/dougbinks/enkiTS/pull/116

**Comment by dougbinks** [comment]
Closed, many thanks for the issue and PRs!
