### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by erincatto** [dougbinks/enkiTS#124]
I'm seeing this all the time lately using enkiTS via CMake.

> CMake Deprecation Warning at build/_deps/enkits-src/CMakeLists.txt:1 (cmake_minimum_required):
> Compatibility with CMake < 3.5 will be removed from a future version of
> CMake.
> 
> Update the VERSION argument <min> value or use a ...<max> suffix to tell
> CMake that the project does not need compatibility with older versions.

It would helpful to bump the version to 3.5. I tested this and it seems fine. I'd submit a PR, but it is a one line change.

**Comment by dougbinks** [comment]
Thanks for this issue report - I'm happy to receive a PR if you want your name in the commit log, but I'm equally happy just to make the change myself.

**Comment by erincatto** [comment]
See #126
