### ISSUE TITLE
Address Sanitizer finding

### ISSUE THREAD

**Issue by erincatto** [dougbinks/enkiTS#125]
I've been doing more sanitizer runs and hit another issue. There are calls to `GetConfig()` that return a structure by value and then code is taking reference to a member of that structure. This is a reference to a temporary variable that is out of scope.

There are several of these:
```
const CustomAllocator& customAllocator = pETS_->GetConfig().customAllocator;
```

I tried a simple fix:
```
CustomAllocator customAllocator = pETS_->GetConfig().customAllocator;
```
And this made ASAN happy.

I can submit a PR if you like.

**Comment by dougbinks** [comment]
Thanks for this issue report - I'm happy to receive a PR if you want your name in the commit log, but I'm equally happy just to make the change myself.
