### ISSUE TITLE
Correctness of TaskScheduler::WakeThreads

### ISSUE THREAD

**Issue by OlegOAndreev** [dougbinks/enkiTS#13]
Hello.

Minor problem: as far as I can understand, there is a race condition between checking for tasks and incrementing m_NumThreadsWaiting in TaskScheduler::WaitForTasks.

1. [worker thread] TaskScheduler::WaitForTasks is called when there are no tasks.
2. [another thread] TaskScheduler::SplitAndAddTask from another thread adds the task, and calls the TaskScheduler::WakeThreads.
3. [another thread] TaskScheduler::WakeThreads checks the m_NumThreadsWaiting and does not signal event.
4. [worker thread] No tasks are found, worker thread increments m_NumThreadsWaiting. EventWait is called, sleeping the thread until EventSignal is called next time, even when the thread could be processing the added task.

In my opinion, the best way to fix this would be
1. Changing the Event interface to Semaphore interface: SemaphorePublish(int count) + SemaphoreWait().
2. Changing the TaskScheduler::WaitForTasks so that it double-checks the pipes after incrementing m_NumThreadsWaiting.

This algorithm is very similar to benaphore (atomic counter + kernel semaphore) described in http://preshing.com/20150316/semaphores-are-surprisingly-versatile/

I will happily a pull-request with a fix if you'd like. Notice that this also fixes the #12

**Comment by dougbinks** [comment]
Thanks again for the post. This issue is indeed related to #12, and as per my comment there I was planning to move to a semaphore based design (which is partially in progress), i.e. no. 1. on your list.

I'm happy to leave both these open until I finish the fix, I'd rather do the work myself as I have an in progress change already.

**Comment by dougbinks** [comment]
The new implementtation using semaphore's should resolve this, as the waiter count is now incremented outside the check for task loop.
