### ISSUE TITLE
Could you state the purpose of this library more clearly?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [dougbinks/enkiTS#16]
Is this an alternative to Intel TBB, firing multiple threads with different priorities for different tasks?

What problems does it solve?

P.S. For me the only reason for using some custom scheduling system is to reduce latency for very small tasks (because yield tends to switch off the thread for 5-60ms under heavy load from other threads).

**Comment by dougbinks** [comment]
This is a lightweight tasking library, like TBB it tackles the issue of multithreaded programming via the task model. [Intel's TBB has a decent overview of why tasks are often preferred over just using threads](https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Task-Based_Programming.html).

**Comment by dougbinks** [comment]
I'm closing this issue as hopefully being resolved for you.
