### ISSUE TITLE
Unexpected behaviour with ITaskSet MinRange

### ISSUE THREAD

**Issue by sergof** [dougbinks/enkiTS#17]
Hi Doug,

hopefully I'm not misunderstanding the intent of MinRange, but I found that it doesn't behave as expected.
There's a comment saying that the last partition will be smaller than MinRange if SetSize is not a multiple of MinRange, but this is only true if MinRange is larger than NumPartitions of the TaskScheduler.
So you will get partitions smaller than MinRange even if SetSize is a multiple of MinRange.

Furthermore you often (most of the time?) want partitions that are a multiple of MinRange e.g. for alignment reasons.

One way of fixing this is to align NumPartitions and NumInitialPartitions up to the next multiple of MinRange in AddTaskSetToPipe().
So you'd have something like this:
```diff
diff --git a/src/TaskScheduler.cpp b/src/TaskScheduler.cpp
index 187673a..7b1e394 100644
--- a/src/TaskScheduler.cpp
+++ b/src/TaskScheduler.cpp
@@ -327,16 +327,19 @@ void TaskScheduler::SplitAndAddTask( uint32_t threadNum_, SubTaskSet subTask_,
        WakeThreads();
 }
 
+#define IS_POW2(n) ((((n) & ((n) - 1)) == 0) && ((n) != 0))
+#define ALIGN_UP(n, alignment) (((n) + (alignment) - 1) & ~((alignment) - 1))
 void    TaskScheduler::AddTaskSetToPipe( ITaskSet* pTaskSet )
 {
+    assert(IS_POW2(pTaskSet->m_MinRange);
        // set running count to -1 to guarantee it won't be found complete until all subtasks added
     pTaskSet->m_RunningCount = -1;
 
     // divide task up and add to pipe
-    pTaskSet->m_RangeToRun = pTaskSet->m_SetSize / m_NumPartitions;
+    pTaskSet->m_RangeToRun = pTaskSet->m_SetSize / ALIGN_UP(m_NumPartitions, pTaskSet->m_MinRange);
     if( pTaskSet->m_RangeToRun < pTaskSet->m_MinRange ) { pTaskSet->m_RangeToRun = pTaskSet->m_MinRange; }
 
-       uint32_t rangeToSplit = pTaskSet->m_SetSize / m_NumInitialPartitions;
+       uint32_t rangeToSplit = pTaskSet->m_SetSize / ALIGN_UP(m_NumInitialPartitions, pTaskSet->m_MinRange);
        if( rangeToSplit < pTaskSet->m_MinRange ) { rangeToSplit = pTaskSet->m_MinRange; }
 
     SubTaskSet subTask;
```
This way things would work as before when MinRange is 1 and as long as SetSize is a multiple of MinRange so will be the partitions.
If MinRange is a power of 2 then this doesn't add much overhead, which is an acceptable restriction for me, not sure it is for others though.

What do you think, is there a better way of dealing with this?

**Comment by sergof** [comment]
Actually thinking about it more, just aligning up isn't enough, we'd have to make sure the numbers of partitions are powers of 2 as well.

**Comment by dougbinks** [comment]
In order to handle alignment and keep to powers of 2 I recommend that you compute a mapping from m_SetSize to your data which meets this.

So if you take a simple example of an array of 1024 bytes which you want process in chunks aligned to 64 bytes you would use a m_SetSize of 16 and then multiply the range start and end by 16 before you run your computation.

**Comment by dougbinks** [comment]
To clarify the above - I'm proposing this should be handled in your code rather than in the task scheduler.

**Comment by sergof** [comment]
Yeah, that's what I have been doing, I just thought that since we have the min range parameter it would be neat if I didn't have to :)

Btw, thanks for working on this project, it helped me out a lot.

**Comment by dougbinks** [comment]
The minimum range is really only intended as a simple way to ensure the scheduler doesn't split work up into too many pieces. Anything more complex tends to have domain specific needs which are best handled in user code.

I should add some more clarity to this in the readme though.

**Comment by sergof** [comment]
Ok, thanks for clearing things up.

**Comment by dougbinks** [comment]
Thanks for the issue!
