### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [dougbinks/enkiTS#18]
Would you like to [wrap any pointer data members](https://github.com/dougbinks/enkiTS/blob/ed71b00e9118b3a77fda1440198410028bd35c63/src/TaskScheduler.cpp#L142 "Update candidate: TaskScheduler class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by dougbinks** [comment]
No. This would not help in any way.

I'd blocked you before, but it appears that this has changed, so blocking you again.
