### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [dougbinks/enkiTS#2]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition.") ⇒ [EventWait](https://github.com/dougbinks/enkiTS/blob/2af8fd9110684291c55b629cb60f8241029bb48c/src/Threads.h#L150)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [EventSignal](https://github.com/dougbinks/enkiTS/blob/2af8fd9110684291c55b629cb60f8241029bb48c/src/Threads.h#L169)

**Comment by dougbinks** [comment]
If it can be shown to be useful, then yes.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

**Comment by dougbinks** [comment]
Please be concrete - for example propose a pull request or demonstrate an issue (observed or potential).

**Comment by elfring** [comment]
How do you think about to make sure that the affected Pthread function calls really succeeded?

**Comment by dougbinks** [comment]
enkiTS' use of the EventWait and EventSignal is robust under the failure of these function calls.

**Comment by elfring** [comment]
Would you like to detect every error situation as early as possible?

**Comment by dougbinks** [comment]
I'm going to leave this open for the moment as I think that improved error handling is a reasonable goal. However I'd be very appreciative of more information on what it is that you think the logic should be for handling these errors.

**Comment by dougbinks** [comment]
I've found that [you have filed this same vague issue with multiple projects](https://github.com/search?q=elfring+completion+of+error+handling&type=Issues&utf8=%E2%9C%93), along with other similarily vague issues.

I'm closing this issue, reporting and blocking you.
