### ISSUE TITLE
m_pPinnedTaskListPerThread not initialized

### ISSUE THREAD

**Issue by codingfred** [dougbinks/enkiTS#20]
Hello,
in the C++11 branch there is a small oversight. In the constructor of TaskScheduler.cpp `m_pPinnedTaskListPerThread  `is not initialized with `NULL`. When then calling the `Initialze()` method the `delete[]` operator will try to delele `m_pPinnedTaskListPerThread `(whatever it points to...) and it will crash on runtime when compiled under Linux. MSVC (Visual Studio 15.8.6)  will ignore? this (it runs at least without crashing).

On the master Branch `m_pPinnedTaskListPerThread `ist correctly set to `NULL `in the constructor.

I would normally suggest (for the C++11 branch) to switch to `std::unique_ptr` but I understand if you do not want too much divergence in the implementations between the master and C++11 branch.

Thanks for this great and easy to use library.
Best wishes,
Fred

**Comment by dougbinks** [comment]
This does look like a bug, thanks for catching.

I'll fix that asap.

**Comment by dougbinks** [comment]
If you can confirm this issue is fixed then please close, many thanks once again!

**Comment by codingfred** [comment]
Thanks for the fast response anderen the quick fix. Will Report asap back to you!
