### ISSUE TITLE
Inconsistent behavior on ARM architecture

### ISSUE THREAD

**Issue by Jackal-one** [dougbinks/enkiTS#24]
Hello!

I've been successfully using `enkiTS` on different platforms based on `x86_64` and it works just fine. After I ported my project on `ARM` (NVIDIA Tegra) I've noticed inconsistent behavior. I tried to run the examples on the target and `TasksThroughput` either deadlocks or reports wrong check count.
It appears to be an issue related to memory reordering, has this library been used/tested on `ARM` before?

Thanks

**Comment by dougbinks** [comment]
It looks like I accidentally removed a line about the code not being well tested on ARM (iOS and Android ) from the readme, I will re-add that shortly and hopefully get around to testing on Android soon.

enkiTS was working on an older version of the code, but it looks like I've broken something with this release and I can only test occasionally on ARM as I currently only have occasional access to an ARM system.

**Comment by Jackal-one** [comment]
As an update, I've tried `C++98` branch and it seems to work fine so far.

**Comment by dougbinks** [comment]
Thanks - that's good news, and may help me pin down the problem!

Many thanks for investigating and reporting this.

**Comment by dougbinks** [comment]
I've been able to confirm this issue on an Android ARM device and am investigating.

**Comment by dougbinks** [comment]
I now have a potential fix on branch dev, I'll do some further testing before merging to master.

If you have the time it would be great to know if this resolves the problem on your system as well.

**Comment by Jackal-one** [comment]
I've quickly tried `dev` branch and `TaskThroughput` seems deterministic on my system. Thanks a lot.

**Comment by dougbinks** [comment]
Many thanks! Testing continuing here with no problems found so far, so I should release this to master soon.
