### ISSUE TITLE
Small tweaks to repository

### ISSUE THREAD

**Issue by ScrappyCocco** [dougbinks/enkiTS#25]
* The "example folder" link in the readme is broken, it still search for a folder that no longer exist
* There's a small typo here (cab instead of can, nothing dangerous): https://github.com/dougbinks/enkiTS/blob/175238ff19caf994bfd2d5ef78e7d3071df67299/src/TaskScheduler.h#L147

**Comment by dougbinks** [comment]
Thanks for finding these! I'll fix them shortly.
