### ISSUE TITLE
Pinned task bug ?

### ISSUE THREAD

**Issue by zhaijialong** [dougbinks/enkiTS#28]
Hi.

I wrote some simple test code for pinned task. After it runs a few seconds, it hit the assert:
```
Assertion failed: pTailPlus1->pNext, file E:\Source\enkiTS-master\src\LockLessMultiReadPipe.h, line 275
```

Here is my code:
```
TaskScheduler g_TS;

std::atomic_uint32_t foo = 0;

struct PinnedTaskHelloWorld : IPinnedTask
{
    PinnedTaskHelloWorld()
        : IPinnedTask(1) // set pinned thread to 1
    {}
    virtual void Execute()
    { 
        printf("This will run on the thread 1, %d\n", foo++);
    }
};

PinnedTaskHelloWorld task[100];

int main(int argc, const char * argv[])
{
    g_TS.Initialize(2);

	while (true)
	{
		for (int i = 0; i < 100; ++i)
		{
			g_TS.AddPinnedTask(&task[i]);

			if (i == 50)
			{
				g_TS.WaitforAll();
			}
		}
	}

    return 0;
}

```

Did I got something wrong ? I'm on VS2019 x64 build.

Thanks.

**Comment by dougbinks** [comment]
This could indeed be a bug.

I'll be away from my PC today, but I think the issue here might be that the line:

```
                    if( !pHead.compare_exchange_weak( pTailPlus1, &tail ) )
```
Should be:
```
                    if( !pHead.compare_exchange_strong( pTailPlus1, &tail ) )
```
I should be able to get to my PC on Sunday and check this out.

**Comment by zhaijialong** [comment]
I'm afraid it's not. I change it to `compare_exchange_strong`, and still got the issue.

**Comment by dougbinks** [comment]
Oh well! Thanks for the report and I'll check it out when I get to my PC tomorrow.

**Comment by zhaijialong** [comment]
Ok, Thank you.

**Comment by dougbinks** [comment]
This was indeed a bug, and it should now be fixed - please close if this works for you, otherwise I'll close shortly.

**Comment by zhaijialong** [comment]
Yeah, it works. Thank you.

And there is another issue( can't compile on vs2015) in the new code, I will open another issue .

**Comment by dougbinks** [comment]
Glad this works, many thanks for finding this issue.
