### ISSUE TITLE
C++11 Branch doesn't Build on OSX Mavericks

### ISSUE THREAD

**Issue by yamamushi** [dougbinks/enkiTS#3]
```
/projects/enkiTS/src/TaskScheduler.cpp:38:8: error: thread-local storage is unsupported for the current target
static thread_local uint32_t                             gtl_threadNum       = 0;
       ^
1 error generated.
```

Based off of what I read here, http://stackoverflow.com/questions/23791060/c-thread-local-storage-clang-503-0-40-mac-osx , I was able to get it to compile by changing thread_local to __thread .

**Comment by dougbinks** [comment]
thread_local is a C++11 storage class specifier, so it appears the XCode install with OSX Mavericks doesn't fully support C++11. You might be better off using the master branch, which [includes the pre-C++11 thread local specifier](https://github.com/dougbinks/enkiTS/blob/master/src/Threads.h#L105).

The current C++11 branch already includes a thread_local workaround for MS Visual Studio version 1800 and below, so I'll look into adding one for this version of the compiler. However for other readers of this please note that I'm not in general going to add support to the C++11 branch for non-compliant implementations as that's what the master branch is for.

**Comment by dougbinks** [comment]
It turns out OSX removed support for thread_local. I can't find out exactly which versions of the compiler have support, nor how to detect easily without using cmake to generate a platform layer (which would mean you couldn't drag & drop the code easily). For now this should work, I'll update once I have more information.

**Comment by dougbinks** [comment]
Many thanks for filing the issue!
