### ISSUE TITLE
can't compile on vs2015

### ISSUE THREAD

**Issue by zhaijialong** [dougbinks/enkiTS#30]
https://github.com/dougbinks/enkiTS/blob/master/src/LockLessMultiReadPipe.h#L277

this line of code can't compile on vs2015, it generate a error `error c2593 'operator ==' is ambiguous`.

I have to change it to ` while( (T*)NULL == pTailPlus1->pNext ) {;}` to make it compiles.

**Comment by dougbinks** [comment]
Once again thanks for finding this, fixed now.
