### ISSUE TITLE
Static TaskScheduler destructor on windows: destructor never returns

### ISSUE THREAD

**Issue by boxerab** [dougbinks/enkiTS#34]
StopThreads goes into an infinite loop. I suppose this has something to do with when the static object is destroyed.

**Comment by dougbinks** [comment]
Does this happen in the example code or your own code?

Since I've not encountered this I'd like to be able to get a reproduction so need as much information as needed to be able to do that.

**Comment by boxerab** [comment]
Thanks for the quick reply! Yes, it's in my code.

https://github.com/GrokImageCompression/grok/blob/master/src/lib/openjp2/T1Encoder.cpp

I can give you some command line arguments if you want to reproduce with my project.
This only happens on windows - all the threads in the pool are waiting for tasks on semaphore,
even after calling StopThreads().

**Comment by boxerab** [comment]
Correction: all threads in the pool have exited, but the main thread is in infinite loop.

Windows 10, VS 2017, 32 bit build.

**Comment by boxerab** [comment]
The problem seems to be that m_NumThreadsRunning did not get decremented down to zero when threads exited.

**Comment by dougbinks** [comment]
Your code is a large project, it might take some time for me to dig into this - are you able to reproduce this in a smaller sample?

I can see two calls to Scheduler::g_TS.Initialize((uint32_t)numThreads) - depending on how these are called this could be an issue.

Also calling enkiTS functions from different threads, other than the tasking thread, can potentially lead to issues. If you initialize on a thread, but do not WaitforAllAndShutdown() on the same thread this might also cause a problem.

**Comment by boxerab** [comment]
Thanks! Indeed, WaitforAllAndShutdown() fixed the problem.

**Comment by dougbinks** [comment]
Great!

**Comment by boxerab** [comment]
By the way, the problem I was experiencing seems to be due to my using a static TaskScheduler object, which is destroyed at process exit, *after* all the task threads have been killed by the OS. So, enkiTS waits forever for threads that it thinks are still running when in fact they have already been destroyed.  Might be worth adding a warning about this in the docs.

**Comment by dougbinks** [comment]
The threads are created by the TaskScheduler object so should only be destroyed when the TaskScheduler itself is destroyed, and most of the examples use a static TaskScheduler object. I think something else is going on and will need to take a look at your example to reproduce the issue once I get some time.
