### ISSUE TITLE
How to prevent master thread from being scheduled?

### ISSUE THREAD

**Issue by vinjn** [dougbinks/enkiTS#38]
enkiTS is an excellent library to serve my project, which is running multiple OpenGL contexts on multiple GPUs.
In my design, master thread is running light-weighted workloads, which means it should never be scheduled to run any `ITaskSet` tasks.
Is it possible?

**Comment by dougbinks** [comment]
Yes this is possible.

Only the threads created by enkiTS will run tasks by themselves. The thread
which initializes enkiTS can tasks using the WaitforTask() call but you can
use the priority system to prevent certain tasks from running when this is
called.

There also exists a pinned task system for explicitly running tasks on
certain threads.

In your case I recommend the master thread initializes enkiTS and you
should then be able to schedule tasks to be run which will then not run on
the master thread.

**Comment by vinjn** [comment]
Thanks @dougbinks 
> you can use the priority system to prevent certain tasks from running when this is called.

Can you give more details? It seems I need to use `WaitforTask` and `ICompletable::m_Priority` to achieve it. But how?

**Comment by dougbinks** [comment]
You only need to run WaitforTask if you need to wait for the task.
Alternatively you can poll for the task to complete and continue running.

If you want to wait for a task to complete, but not run other tasks, you
can give that task a high priority, other tasks lower priorities and when
you wait for the high priority task you specify to only run high priority
tasks whilst waiting. See the readme and priorities example for code.

**Comment by dougbinks** [comment]
I think this question is now answered, so I'm going to close it unless there are any further questions or issues on this topic.
