### ISSUE TITLE
Garbled formatting due to mixed tabs/space usage

### ISSUE THREAD

**Issue by lamarqua** [dougbinks/enkiTS#4]
Title is self-explanatory, the formatting is all messed-up :-)
See for example: 
https://github.com/dougbinks/enkiTS/blob/5b135fd3cdd9bcd851d04b4be778be7b8f727917/src/TaskScheduler.cpp#L72

**Comment by dougbinks** [comment]
This happens from time to time, as I work on a variety of systems and a variety of different projects with different requirements as to tabs and spaces.

With almost all code editors having defaulted to a tab as 4 spaces the only outlier in formatting is the web, which uses 8. Hopefully when the css style tab-size becomes commonly adopted Github will setup code view to use 4 spaces for a tab.

For now I've found the [current solution works well if you're using Chrome](http://stackoverflow.com/questions/19916815/how-to-change-chromes-tab-indention-width). To create a bookmarklet simply use the bookmark manager to add a bookmark and paste the javascript into the second field, and choose a name for the first. Then click it when viewing code on Github.  Alternatively download the code and view in a decent editor - it's lightweight so fast to download!

I'm investigating a git config for the project which filters tabs to spaces in the repo, so developers can then choose which to work with conveniently on their systems. I'll need to do a commit of the code to remove tabs already there though, and this tends to mess up the history a bit.

**Comment by TheEpsylon** [comment]
Actually it looks like one can simply add ?ts=XX at the end of the URL to set tab spacing. Neat!
https://github.com/dougbinks/enkiTS/blob/5b135fd3cdd9bcd851d04b4be778be7b8f727917/src/TaskScheduler.cpp?ts=4#L72

**Comment by dougbinks** [comment]
That's very cool, thanks!

**Comment by dougbinks** [comment]
The latest update to enkiTS had sufficient changes that I felt moving to spaces overall was worth the added confusion to the commit record and so this is now resolved.
