### ISSUE TITLE
Feature: custom allocators

### ISSUE THREAD

**Issue by dougbinks** [dougbinks/enkiTS#41]
Whilst enkiTS only allocates at initialization time, a custom allocator would be useful to some users for tracking memory consumption.

https://twitter.com/serhii_rieznik/status/1187011358220541952

**Comment by sergeyreznik** [comment]
Subscribed :)

**Comment by dougbinks** [comment]
First draft of interface / C++ functionality:
https://github.com/dougbinks/enkiTS/commit/548d714f7be7e36107f104470a29ecc59bd9f9ce#diff-efb8567dc14bae32a01bd1c64bc61ef6

C version and examples to come.

**Comment by sergeyreznik** [comment]
Super!

Probably you can hide implementation and templates into source file, without exposing it in API

**Comment by dougbinks** [comment]
The implementation is in the private: section of the class declaration. I could put some more effort into hiding things in the implementation file but this is always a little more tricky to do that it should be in C++.

**Comment by dougbinks** [comment]
The [dev branch](https://github.com/dougbinks/enkiTS/tree/dev) now has a C interface along with examples for C++ and C interfaces.

**Comment by dougbinks** [comment]
This issue was commented on in https://github.com/dougbinks/enkiTS/commit/94906dff3857b8ff293e6ac538b488f2f0b484c0

**Comment by dougbinks** [comment]
Taking on @brunochampoux's comments in https://github.com/dougbinks/enkiTS/commit/94906dff3857b8ff293e6ac538b488f2f0b484c0#commitcomment-35699354 I've modified the API to include alignment, __FILE__ and __LINE__ macros.

This makes it fairly complex, but hopefully the examples and default allocation functions will act as guides for those using this feature.

**Comment by brunochampoux** [comment]
Hi Doug,

I understand your argument for the alignment parameter and it does make the multi-platform implementation more complex. I generally operate under the assumption that most multi-platform game engines will already have this facility and forget about other use cases :)

I realize your memory usage is very simple and I leave it to you to decide if you want to keep this parameter or if you think it's not necessary. If in the future you need alignment, you can certainly handle it internally by requesting more bytes as you said (but it can be inconvenient to keep track of the offset when you will call `free`).

Regards,
Bruno

**Comment by dougbinks** [comment]
I've added alignment - anyone writing their own allocators for performance reasons should be able to handle this, and if they're just doing memory tracking the examples and default allocators should be sufficient guide to be up and going quickly.

**Comment by bkaradzic** [comment]
You just need one function:

`void* realloc(void* _ptr, size_t _size, size_t _align, const char* _file, uint32_t _line)`

1. When ptr is not NULL and size is 0 that's `free`.
2. When ptr is NULL and size is not 0 that's `malloc`.
3. When ptr is not NULL, and size is not 0 that's `realloc`.

File and line are just for debug builds.

**Comment by brunochampoux** [comment]
I must respectfully disagree. It is much cleaner and simple to have separate alloc/free callbacks with no realloc semantics to deal with.

**Comment by dougbinks** [comment]
I think I'll stick with two functions - the one function idea is neat but since i know the size on free I'm passing it in.

I'm considering adding a macro for controlling whether I pass __FILE__ and __LINE__, though that makes implementations more complex.

**Comment by dougbinks** [comment]
I've added macros to control file_ and line_ use, so release builds won't contain any strings by default, see https://github.com/dougbinks/enkiTS/blob/dev/src/TaskScheduler.h#L47-L53

Hopefully this should be simple enough, but powerful enough for everyone.

**Comment by dougbinks** [comment]
Closed with [release v1.6](https://github.com/dougbinks/enkiTS/releases/tag/1.6)
