### ISSUE TITLE
Trouble with chunking. 

### ISSUE THREAD

**Issue by NPatch** [dougbinks/enkiTS#42]
Hi! First off thanks for this lib. 
On to the issue. I have index buffers which I want to manipulate, therefore I'm operating in triplets of consecutive cells in the flat index buffer. I'm failing though to manage the ranges. 
How would you go about it?

**Comment by DeanoC** [comment]
As they are consecutive, I'd divide by 3 when passing in the range and multiple by 3 in the job. The range can be anything you like as long as it continous.

**Comment by dougbinks** [comment]
@DeanoC's answer is what I'd do.

**Comment by NPatch** [comment]
By range, do you mean MinRange? So MinRange should be SetSize / 3 ?
A bit confused about multiplying inside the job. I figured I could just iterate the range in each task partition in +3 steps(unless that's what you meant by *3) if I could figure out how to chunk them using SetSize and MinRange.

As an example, I have a mesh with 5.000.000 faces(so 15.000.000 verts). I've used SetSize = 15.000.000 and then iterated in a for loop by i+=3.  Tried various values for MinRange thinking that would set the minimum one I encounter inside ExecuteRange.
Would MinRange = 15.000.000 / 3 be correct? As for the multiply by 3 inside the job, does that mean the increment part in the for loop? Or just do i * 3 inside the body?

**Comment by dougbinks** [comment]
Ah, no we were referring to the overall range, or m_SetSize. You should make the set size 15000000/3 and then in the loop multiply by 3 to get your start and end vertices:

m_MinRange is for optimization purposes, and should be left at 1 until you start profiling and optimizing. 

As for what your inner loop looks like, this depends on exactly what you want to do. You would have something like:

```
struct VertTaskSet : ITaskSet
{
    ParallelSumTaskSet( uint32_t numVerts_ ) :  { m_SetSize = numVerts_  / 3; }

    virtual void ExecuteRange( TaskSetPartition range_, uint32_t threadnum_ )
    {
        uint32_t vert_start = range_.start * 3;
        uint32_t vert_end   = range_.end   * 3;
        // do something from vert_start to vert_end
    }
}
```

**Comment by NPatch** [comment]
Yeap, that fixed things!! 

Any rule of thumb for MinRange?

**Comment by dougbinks** [comment]
You want to try to set m_MinRange to a value which results in computation effort of at least 10k clock cycles to minimize task scheduler overhead. So if your inner loop of ExecuteRange has only 10 instructions you might want m_MinRange to be 1000, and if it has 100 you would want m_MinRange to be 100 (this is very approximate since instructions do not translate to clock cycles, but it should be 
 a decent value).

This can be tricky to judge, and it won't make a big difference unless you have a small set size or a large number of cores so can be left as the default.

**Comment by NPatch** [comment]
I see! Thanks!!!
