### ISSUE TITLE
CACHE_LINE_SIZE name clashes with macro from major console SDK

### ISSUE THREAD

**Issue by brunochampoux** [dougbinks/enkiTS#43]
Hi Doug,

I updated *enkiTS* to 1.4 and the new constant `CACHE_LINE_SIZE` ends up clashing with a macro defined in the SDK of a famous video game console which I cannot name due to a NDA.

As you target game development with *enkiTS* I thought you might like to know this.

Personally I see 3 ways to deal with this:
1. Dumb arbitrary rename, say to `SIZE_OF_CACHE_LINE`
2. Prefix all macro and macro-like names with `ENKI_`
3. Use *CamelCase* for all your non-macro symbols

On an unrelated note, I would also recommend that you move all your variables into your `enki` namespace.

Regards,
Bruno

**Comment by dougbinks** [comment]
Thanks for the issue report & suggestions.

I've both wrapped all the variables which weren't already in a namespace into enki:: and changed the name of ```CACHE_LINE_SIZE``` to ```ENKI_CACHE_LINE_SIZE``` since a project level macro would still cause issues. Let me know if this resolves the issue.

**Comment by brunochampoux** [comment]
Looks fine for me. The assignment is now misaligned but that's just my OCD :)
Thanks.
