### ISSUE TITLE
GCC warnings

### ISSUE THREAD

**Issue by boxerab** [dougbinks/enkiTS#44]
GCC complains that size_, userData_ etc are never used in this method:

```
ENKITS_API void  enki::DefaultFreeFunc(  void* ptr_,   size_t size_, void* userData_, const char* file_, int line_ )
{
#ifdef _WIN32
    _aligned_free( ptr_ );
#else
    free( ptr_ );
#endif
};
```

Not a big deal, but the fewer warnings the better :)

**Comment by dougbinks** [comment]
Thanks - looks like i left of the (void) casts on this one. Fixing now...
