### ISSUE TITLE
Question: is it possible for two threads to use the enkiTS api concurrently ?

### ISSUE THREAD

**Issue by boxerab** [dougbinks/enkiTS#45]
I have an encoder and decoder that both are using the api, but they are running in a video pipeline, so encoding and decoding are happening concurrently. Is there a way of safely using the api in this situation ?

**Comment by dougbinks** [comment]
Yes - the enkiTS API can be used from any task thread (i.e. from within any ```IPinnedTask::Execute``` or ```ITaskSet::ExecuteRange``` function), the thread which intiialized the task scheduler and any thread registered using the ```RegisterExternalTaskThread```.

**Comment by boxerab** [comment]
Thanks! I will see I can register the thread.
