### ISSUE TITLE
WaitforAll() and external threads

### ISSUE THREAD

**Issue by Vuhdo** [dougbinks/enkiTS#51]
`WaitForAll()` adds a dummy pinned task and then waits:
https://github.com/dougbinks/enkiTS/blob/4f9941be80affa9296665c8609779acb4e70b327/src/TaskScheduler.cpp#L796

Sometimes `WaitForAll()` won't awake. 

Not sure if it is due to recent changes, but I have never experienced this problem until today 
when I merged the master into my fork.

It seems when this happens the thread we're pinning the dummy task to, is an external thread (added via` RegisterExternalTaskThread()`). In my case this was the dedicated rendering thread - it handles main thread requests and sleeps, never running tasks explicitly, so there's no guarantee it will run the dummy task at all.

**Comment by dougbinks** [comment]
Thanks for the report - I'll take a look at this asap.

**Comment by dougbinks** [comment]
I've posted a potential fix for this issue to the [dev branch](https://github.com/dougbinks/enkiTS/tree/dev), and will look into adding a test for this situation. In the meantime if you're able to try this out it would be very helpful.

**Comment by Vuhdo** [comment]
The fix helped, no more hangs, thanks!

**Comment by dougbinks** [comment]
Thanks - I'll close this and merge to master and add a test at some point, do let me know if you experience any further issues and once again thanks for the report!

**Comment by dougbinks** [comment]
This is now merged to the master branch.
