### ISSUE TITLE
Crash in Android 11 beta

### ISSUE THREAD

**Issue by MSFT-Chris-Barrett** [dougbinks/enkiTS#57]
This is almost certainly an issue on Android's side, not yours, but I wanted to at least bring things to attention.  In enki::DefaultAllocFunc(), non-Win32 programs use posix_memalign().  Our 64-bit Android app is segfaulting at launch, and it seems that the call to posix_memalign() is involved in whatever's going wrong.  If we replace that with a call to plain malloc(), our app carries along running "fine".  By "fine", I mean this isn't significantly tested or shipped beyond my local build going from segfault-at-launch to looking like all's well.

Like I said, probably an Android 11 beta issue-- which I'm testing on a Pixel phone-- but at least wanted to make sure you were aware.

Edit: correction/clarification.  It's not the call to `posix_memalign()` itself that's segfaulting.  When `TaskScheduler::StartThreads()` runs `m_pTaskCompleteSemaphore = SemaphoreNew()`-- the second call to SemaphoreNew()-- the resulting placement-new in TaskScheduler::New() is what's segfaulting.  Even though `posix_memalign()` returned a "success" error code of 0, and the pointer to memory is non-null.

**Comment by dougbinks** [comment]
Thanks for the report  - I'll take a look at what I can do.

**Comment by dougbinks** [comment]
I have a potential fix for this on the /dev branch: https://github.com/dougbinks/enkiTS/tree/dev

If you have time to test (I don't have Android 11) that would be very useful.

**Comment by MSFT-Chris-Barrett** [comment]
Looks like I'll need to update in general, since our copy doesn't have an Alloc in TaskScheduler.  But I'll give this a try and get back to you.  Thanks for the quick update!

**Comment by dougbinks** [comment]
Those were added as part of the fix, see the diff:

https://github.com/dougbinks/enkiTS/compare/dev

**Comment by MSFT-Chris-Barrett** [comment]
Ah right, I'd only looked at the commit that referenced this PR, not the dev branch.  Thanks!

So it looks like this has the effect of not calling placement-new, and instead passing the memory with undefined data returned by posix_memalign() over to sem_init().  I'm seeing a segfault now in sem_init() instead of placement-new, so it looks like the underlying issue is unchanged.  That for some reason posix_memalign() on 64-bit Android 11 is giving back memory we're not allowed to write to.

For more information, here's the disassembly of where it's crashing in sem_init().  Though I have to admit it's been some years since I've had reason to look at anything at this level, so I'm not getting much (yet) from looking at this.
```
sem_init:
0x00000070ff074654  stp	x29, x30, [sp,#-16]! 
0x00000070ff074658  mov	x29, sp 
0x00000070ff07465c  lsr	w9, w2, #30 
0x00000070ff074660  cbz	w9, 0x70ff07467c <sem_init+40> 
0x00000070ff074664  bl	0x70ff0cc420 <__errno@plt> 
0x00000070ff074668  mov	w8, #0x16                  	// #22 
0x00000070ff07466c  str	w8, [x0] 
0x00000070ff074670  mov	w0, #0xffffffff            	// #-1 
0x00000070ff074674  ldp	x29, x30, [sp],#16 
0x00000070ff074678  ret 
0x00000070ff07467c  cmp	w1, #0x0 
0x00000070ff074680  cset	w9, ne 
0x00000070ff074684  mov	x8, x0 
0x00000070ff074688  bfi	w9, w2, #1, #31 
0x00000070ff07468c  mov	w0, wzr 
0x00000070ff074690  str	w9, [x8] 
0x00000070ff074694  ldp	x29, x30, [sp],#16 
0x00000070ff074698  ret 
0x00000070ff074698  ret 
```
With Visual Studio's yellow arrow pointed at the `0x00000070ff074690  str	w9, [x8]` line.

**Comment by dougbinks** [comment]
On the dev branch I've added a test for whether malloc can be used in place of posix_memalign, and use that instead. I'm hoping this should work for sem_t on Android 11, but if not I can come up with a slightly better test.

Do you know what align_ and size_ are for the semaphores struct on Android 11?

**Comment by MSFT-Chris-Barrett** [comment]
I'm seeing `alignof(semaphoreid_t)` 64, and `sizeof(semaphoreid_t)` 16.  Also confirmed that __LP64__ is set on this platform with just a dummy #error 'test' line added to where __LP64__ would change the size of the semaphore type.

I think both alignof(uint32_t) and sizeof(uint32_t) are 4, which will cause malloc to be used in your most recent changes.  I'll try those out, too.

**Comment by MSFT-Chris-Barrett** [comment]
I haven't been able to get reliable information out of the app running on a phone with Visual Studio's debugger attached.  So, scratch my last information about malloc getting used with the dev branches latest changes.  That was from a breakpoint with an action to print information, which turns out to not have been accurate.

Using the latest changes, posix_memalign is still used for semaphoreid_t.  Upside: that makes sense since `__LP64__` is set (making the semaphoreid_t type's sem_t four `int`s).

**Comment by dougbinks** [comment]
I've now merged this fix to master.
