### ISSUE TITLE
Support for custom asserts

### ISSUE THREAD

**Issue by BobbyAnguelov** [dougbinks/enkiTS#63]
Hey,

I have a bit of a custom/strange setup wherein I link against the runtime CRT in debug builds, so I have NDEBUG defined globally, which disable the std asserts.

Would it be possible to switch over to using a macro or something instead of assert( X )? That way a user can easily replace the asserts in enkiTS with their own custom ones.

**Comment by dougbinks** [comment]
This has been on my list of things to do for a while, and would also be helpful in my own work, so I'll get on to it shortly.

**Comment by dougbinks** [comment]
I have an initial implementation in the [branch dev_enki_assert](https://github.com/dougbinks/enkiTS/tree/dev_enki_assert). Let me know if this is sufficient for your needs and if so I'll merge into master.

**Comment by BobbyAnguelov** [comment]
Works for me :)

**Comment by dougbinks** [comment]
This is now merged to master - I'll add readme and comment notes later. Thanks for proposing & testing!

**Comment by BobbyAnguelov** [comment]
The change is incomplete. 

Ln188, ln463 and ln477 need to be changed from assert to ENKI_ASSERT

**Comment by dougbinks** [comment]
Thanks - I also missed the ones in the C version, will fix now.

**Comment by dougbinks** [comment]
Hopefully the latest commits fix this. I've not switched the example code to these asserts for easier readability.
