### ISSUE TITLE
Warning regarding padding with VS 2019 16.11.7

### ISSUE THREAD

**Issue by BobbyAnguelov** [dougbinks/enkiTS#67]
Just integrated v1.10 and have this: warning C4324: 'enki::ThreadDataStore': structure was padded due to alignment specifier.

I'm gonna suppress the warning on my side as I have warnings as errors on, but maybe it would be good to pad it manually?

**Comment by dougbinks** [comment]
Looks like I forgot to modify the prevent_false_Share size, I've altered that and added a better static_assert. Will double check tomorrow and push a fix.

Thanks for the report!

**Comment by dougbinks** [comment]
I've pushed the changes to the dev branch, will merge to master after further testing.

**Comment by dougbinks** [comment]
This is now merged into master so I'll close this issue, but if you still find the warning do re-open it and I'll figure out what I missed.
