### ISSUE TITLE
parallel_for label:question 

### ISSUE THREAD

**Issue by ib00** [dougbinks/enkiTS#73]
Is there a simple implementation of parallel_for on top of enkiTS?

**Comment by dougbinks** [comment]
The `ExecuteRange` virtual function of an `ITaskSet` provides a parallel_for style interface.

So for example if you have a simple for loop such as:

```
for( int i = 0; i < count; ++i )
{
     a[i] = b[i] * c[i];
}
```

you can replace this with a lambda `TastSet` with set size equal to `count`, and the following task implementation:

```
// following is untested code
enki::TaskScheduler g_TS;
g_TS.Initialize();

enki::TaskSet task( 1024, [&]( enki::TaskSetPartition range, uint32_t threadnum  )
{  
    for( uint64_t i = range_.start; i < range_.end; ++i )
    {
         a[i] = b[i] * c[i];
    }
} );

g_TS.AddTaskSetToPipe( &task );
g_TS.WaitforTask( &task );
```

You could create a function which takes a lambda and does the above (except for initializing enkiTS which should usually be done only once).

**Comment by ib00** [comment]
Thanks! I presume that TaskSet idea would also work with C API.

**Comment by ib00** [comment]
Thanks! With minor modification, I can confirm that both C++ and C versions you gave 
work nicely.

I appreciate you making this library available.
