### ISSUE TITLE
Minor memory leak

### ISSUE THREAD

**Issue by fstrugar** [dougbinks/enkiTS#8]
Hey, just noticed this using the _CrtMemCheckpoint/_CrtMemDifference/_CrtDumpMemoryLeaks - in C++11 version, the std::thread objects are created on the heap in TaskScheduler.cpp line 148:

`m_pThreads[thread] = new std::thread( TaskingThreadFunction, m_pThreadNumStore[thread] );`

but there's no corresponding delete. I've added it to StopThreads just before m_NumThreads = 0, updated function:

```
void TaskScheduler::StopThreads( bool bWait_ )
{
    if( m_bHaveThreads )
    {
        // wait for them threads quit before deleting data
        m_bRunning = 0;
        while( bWait_ && m_NumThreadsRunning )
        {
            // keep firing event to ensure all threads pick up state of m_bRunning
           m_NewTaskEvent.notify_all();
        }

        for( uint32_t thread = 1; thread < m_NumThreads; ++thread )
        {
            m_pThreads[thread]->join();
            delete m_pThreads[thread];
        }

	m_NumThreads = 0;
        delete[] m_pThreadNumStore;
        delete[] m_pThreads;
        m_pThreadNumStore = 0;
        m_pThreads = 0;

        m_bHaveThreads = false;
	m_NumThreadsActive = 0;
	m_NumThreadsRunning = 0;
    }
}
```

->join is needed to prevent asserts. Also, maybe m_pThreads could be just * instead of **, no need to create each std::thread object separately on the heap? 

std::thread*	m_pThreads;
....
m_pThreads[thread] = std::thread( TaskingThreadFunction, m_pThreadNumStore[thread] );

should work too? I'm not 100% sure, my c++11-fu isn't that great :)

**Comment by dougbinks** [comment]
Thanks - I'll look into this when I'm able in a few days.

**Comment by dougbinks** [comment]
This should now be fixed. I've used detach rather than join as if bWait_ is false the thread may still be processing a task (note that using bWait_ false is dangerous since the thread is likely to crash on accessing resources which are no longer available).
