### ISSUE TITLE
Stall in the C++11 when overflowing the pipe in AddTaskSetToPipe

### ISSUE THREAD

**Issue by fstrugar** [dougbinks/enkiTS#9]
When adding more than (1<<PIPESIZE_LOG2) elements using AddTaskSetToPipe, once the pipe is full it will start executing subtasks inplace but if the other worker threads are asleep, they will not be awaken. 

My simple fix was to add 
```
        // wake up threads early
        if( ( numAdded % 128 ) == 0 )
        {
            if( m_NumThreadsActive.load( std::memory_order_relaxed ) < m_NumThreadsRunning.load( std::memory_order_relaxed ) )
            {
                m_NewTaskEvent.notify_all( );
            }
        }
```
just after the if( !m_pPipesPerThread[gtl_threadNum].WriterTryWriteFront(...) ) { ... } block.

**Comment by dougbinks** [comment]
With the current task scheduler this shouldn't happen unless the number of threads in the system is > 16, which is potentially the case with some systems.

Note that @fstrugar has a modified scheduler which has grain size control allowing tasks to be split up with more control than the current enkiTS.

I'm marking this as both a bug and a feature as this is related to two features I have been looking into doing: 

1. Adding grain size control
2. Optimizing task insertion by offloading some of the splitting to other threads (note offloading all splitting is slower in tests).

**Comment by dougbinks** [comment]
See Issue #10 as I've started grain size control and optimization of task insertion for systems with large numbers of hardware threads.

**Comment by dougbinks** [comment]
I believe the recent commit linked to above along with the grainsize and task addition changes should fix this. As I'm not heard back from you since the creation of this issue I'll close it.
